# PlatformIO pre-build script: writes src/build_info.cpp with the git revision and build time.
# Only that one file changes per build, so it costs a single recompile + link.
import os
import subprocess
from datetime import datetime

Import("env")

project_dir = env["PROJECT_DIR"]

try:
    rev = subprocess.check_output(
        ["git", "describe", "--always", "--dirty", "--tags"],
        cwd=project_dir, stderr=subprocess.DEVNULL,
    ).strip().decode("utf-8")
except Exception:
    rev = "unknown"

built = datetime.now().astimezone().strftime("%Y-%m-%d %H:%M %z")

content = (
    "// Generated by scripts/build_info.py on every build - do not edit\n"
    '#include "build_info.h"\n'
    'const char FW_GIT_REV[] = "%s";\n'
    'const char FW_BUILD_TIME[] = "%s";\n' % (rev, built)
)

path = os.path.join(project_dir, "src", "build_info.cpp")
try:
    with open(path, "r", encoding="utf-8") as f:
        unchanged = f.read() == content
except OSError:
    unchanged = False
if not unchanged:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
